TARGET_DEVICE=$1
export ORIGINAL_BASE_PATH=$PWD
export BOOT_PART_DEVICE=${TARGET_DEVICE}1
export ROOT_PART_DEVICE=${TARGET_DEVICE}2

export DISTRO=ubuntu
export DIST_VER=21.10
export TYPE=server
export ARCH=armhf
export IMAGE_NAME="${DISTRO}-${DIST_VER}-preinstalled-${TYPE}-${ARCH}+raspi.img"
export IMAGE_COMPRESSED_NAME=${IMAGE_NAME}.xz

export REMOTE_IMAGE_HOST="https://cdimage.ubuntu.com/releases/${DIST_VER}/release/"
export REMOTE_IMAGE_TARGET=${REMOTE_IMAGE_HOST}/${IMAGE_COMPRESSED_NAME}

export CACHE_PATH=cache
export CACHED_ORIGINAL_IMAGES=${CACHE_PATH}/ORIGINAL_IMAGES
export CACHED_ENLARGED_IMAGES=${CACHE_PATH}/ENLARGED_IMAGES

export BASE_IMAGE=${CACHED_ORIGINAL_IMAGES}/${IMAGE_NAME}
export ENLARGED_IMAGE=${CACHED_ENLARGED_IMAGES}/enlarged-${IMAGE_NAME}

mkdir -p ${CACHED_ORIGINAL_IMAGES}
mkdir -p ${CACHED_ENLARGED_IMAGES}
